Wr/convert scripts
salesforcecli/plugin-dev pull request #306
Opened 2023-04-20 17:36 UTC by WillieRuemmele

### What does this PR do?
adds a `convert script` command to help people migrate to `sf`

### What issues does this PR fix or reference?
@W-12942991@
https://github.com/forcedotcom/cli/issues/2071

--- 
QA Setup:

`sfdx/sf plugins link .` this repo
`sfdx dev convert script`

running with `./bin/dev` won't result in a complete command list and will fail to convert most commands

2023-05-02 18:17 UTC, iowillhoit commented on messages/convert.script.md
> +
Replace the boilerplate values in this file ^

2023-05-02 18:44 UTC, iowillhoit commented on src/commands/convert/script.ts
> +            this.warn(`Cannot determine appropriate replacement for ${commandId}`);
Might me nice to offer the line number here also

2023-05-02 19:11 UTC, WillieRuemmele commented on src/commands/convert/script.ts
> +      path.basename(flags.script, path.extname(flags.script)) + '-converted' + path.extname(flags.script),
ok - I just changed that yesterday based on Juliet's feedback. I'll add a message

2023-05-02 19:25 UTC, iowillhoit commented
A few thoughts and questions:
- Is there a reason this new command was not added to the existing `src/dev/convert` directory? 
- Should we move the new `Manifest.ts` file alongside the `convert/script.ts` file since that is all it is used for? 
- I am concerned the `Manifest.ts` is going to get out of date and provide incorrect suggestions. What do you think? Is it worth trying to regenerate the oclif manifest as a pre-push or in a cron in GHA?

2023-05-02 19:34 UTC, iowillhoit commented on src/commands/convert/script.ts
> +    return prompt ? await this.confirm(message, 100000) : true;
This timeout might still be a little short. I was curious about a suggestion and went to look if it was correct and it had timed out by the time I got back. Maybe 3 minutes? 180000

2023-05-03 22:26 UTC, iowillhoit commented
Minor QA
- Also log a warning to stdout when "human intervention required", otherwise it looks like it converts successfully.
  - Maybe also log the `deprecationOptions.message` if it exists?
- Wrap commands in quotes to make them easier to read (especially space delimited)
- Add "command" and "flag" to the prompts?
- Change 'replacing' to 'replace' since it's a question
- Before
 ```
replace force:org:create for force org create Yes
? 	replacing f for definitionfile Yes
? 	replacing a for setalias Yes
```
- After
```
replace command "force:org:create" for "force org create" Yes
? 	replace flag "f" for "definitionfile" Yes
? 	replace flag "a" for "setalias" Yes
```

2023-05-05 15:58 UTC, iowillhoit commented
## QA NOTES

- 🟡 Any command with `-h` or `--help` will fail
- 🔴 Any command with `--json` will fail
- 🔴 Any command with `--verbose` will fail
- 🟡 For some reason this convert is failing (seems right to me)
  - `sfdx force:package:install --package 0Ho4p0000004D99CAE`
  - `sf package install --package 0Ho4p0000004D99CAE # ERROR converting this line, human intervention required`
- 🟢 Works on a non-installed JIT plugin
- 🟢 The `--no-prompt` flag works
- 🟡 If the command you are converting already has spaces, `sfdx` is not converted to `sf`
  - `sfdx scanner rule describe` remains `sfdx scanner rule describe`
- 🔴 Oh, it looks like all commands with "long flags" are failing
  - Another `sfdx force:org:list --all`

FWIW, I ran this on my `.zsh-history` to get a wide variety of commands. Might be useful

Here are some additions to put in the `script.sh` for testing:

```
sfdx force:source:status --json
sfdx force:org:list
sfdx force:org:list -h
sfdx force:org:list --json
sfdx force:org:list --verbose
sfdx force:org:list --all
sfdx scanner:rule:list
sfdx scanner rule describe
sfdx force:package:install --package 04t1I0000000X0P
```

2023-05-05 16:17 UTC, jshackell-sfdc commented on messages/dev.convert.script.md
> +This command can convert a large part of your script, but possibly not all. There are some sfdx-style commands that don't have an obvious sf-style equivalent. In this case, this command doesn't repla
```suggestion
This command can convert a large part of your script, but possibly not all. There are some sfdx-style commands that don't have an obvious sf-style equivalent. In this case, this command doesn't replace the sfdx-style command but instead adds a comment to remind you that you must convert it manually. See the Salesforce CLI Command Reference for migration information about each deprecated sfdx-style command: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm.
```

2023-05-05 16:41 UTC, iowillhoit approved these changes

2023-05-05 20:12 UTC, peternhale requested changes

2023-05-05 20:56 UTC, merged